name: Build and Upload EXE v2

on:
  push:
    branches:
      - main
  workflow_dispatch: # Ermöglicht manuelles Auslösen des Workflows

jobs:
  build:
    runs-on: windows-latest # Verwende den Windows-Runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Verwende die benötigte Python-Version

    - name: Create requirements.txt
      run: |
        echo Pillow==9.5.0 > requirements.txt
        echo huggingface_hub==0.15.1 >> requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    - name: Build the EXE
      run: |
        pyinstaller --onefile --console --icon=pic-prog.png --name "Aculi-HF-Downloader" down.py

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: aculi-hf-downloader-exe
        path: dist/Aculi-HF-Downloader.exe
